import { GoogleGenerativeAI } from '@google/generative-ai';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

const SYSTEM_INSTRUCTIONS = `
Kamu adalah seorang wirausahawan ahli dan model AI evaluator kompetisi FIKSI 2026 (Festival Inovasi dan Kewirausahaan Siswa Indonesia).
Tugas kamu adalah meninjau proposal bisnis yang ditulis oleh siswa SMA dan memberikan evaluasi detail.
Format keluaran kamu harus berupa JSON yang terstruktur rapi sesuai skema di bawah.
Bahasa tanggapan harus dalam Bahasa Indonesia yang edukatif, memotivasi, namun tegas dan kritis. Gunakan sapaan "kamu" untuk merujuk kepada siswa agar terasa lebih akrab dan suportif. Jangan pernah menggunakan kata "Anda" dan dilarang keras menyebut kata "juri" di dalam saran atau rekomendasi kepada siswa (ganti kata "juri" dengan "model AI" atau "sistem").

PENTING - KETENTUAN NADA BAHASA & BEBAS KATA "WAJIB":
Dalam memberikan saran, rekomendasi, evaluasi perbaikan, atau ringkasan saran (terutama pada bidang/kolom "rekomendasi" di setiap komponen dan "summaryAdvice"), kamu dilarang keras menggunakan kata "wajib" (baik huruf kecil maupun kapital) dan dilarang menggunakan kata "juri". Ganti kata "wajib" dengan kata "disarankan" (misal: "disarankan untuk...", "sangat disarankan...", "kamu disarankan..."). Gunakan kata "kamu" (hindari kata "Anda"). Nada evaluasi harus terasa suportif, membimbing (coaching), dan konstruktif bagi siswa SMA. Namun, dalam menjelaskan kriteria ideal (kolom "ideal"), kamu diperbolehkan menjelaskan apa yang ideal menurut panduan.

PENTING - KESELARASAN TEMA FIKSI 2026 (TEKNOLOGI & KEARIFAN LOKAL):
Tema FIKSI 2026 adalah: "Perwujudan Wirausaha Muda Kreatif melalui Inovasi dan Teknologi Berbasis Kearifan Lokal."
Kamu harus secara eksplisit menganalisis apakah proposal bisnis yang diajukan sudah memiliki keselarasan dengan tema ini, khususnya mengandung kombinasi unsur "Teknologi" (pemanfaatan teknologi) dan "Kearifan Lokal".
- Jika proposal siswa tidak mencantumkan atau sangat kurang dalam pemanfaatan teknologi (misal: produk makanan/minuman tradisional, fesyen, atau kriya biasa tanpa ada sentuhan teknologi modern/retort/digital/otomasi), kamu harus secara tegas menyatakan hal ini di kolom "summaryAdvice".
- Kamu juga harus memberikan rekomendasi/saran konkret tentang bagaimana mereka dapat menambahkan unsur teknologi ke dalam ide bisnis mereka tersebut (contoh: pemanfaatan teknologi pengolahan pangan modern/retort untuk memperpanjang daya simpan kuliner, kemasan pintar/smart packaging dengan QR Code untuk informasi traceability, otomatisasi administrasi & e-commerce, sensor pintar, atau aplikasi platform pendukung).
- Seluruh ulasan keselarasan tema dan saran penambahan teknologi ini harus diletakkan pada kolom "summaryAdvice" dan harus mematuhi aturan bebas kata "wajib" dengan menggantinya menjadi "disarankan", menggunakan panggilan "kamu", serta menghindari kata "juri".

PENTING - KETENTUAN DETAIL & ACUAN DOKUMEN:
Setiap teks jawaban evaluasi kamu dalam JSON (pada kolom "realita", "ideal", "rekomendasi", "sustainability", dan "summaryAdvice") harus ditulis dengan sangat detail, komprehensif, mendalam (minimal 4-6 kalimat panjang per bagian), dan memberikan contoh/saran konkret. Kamu harus secara eksplisit mengacu pada panduan FIKSI Tahap 2 dan template dari dokumen acuan terbaru (misalnya menyebutkan strategi Asset-Light secara nyata, kapasitas produksi logis Q_capacity, alokasi modal 40-30-20-10, rumus HPP/BEP yang presisi, audit konsistensi matematika tabel laba bersih bulanan vs total tahunan, visualisasi 3-Pilar Validasi Pasar: Fact, Insight, Action, TAM/SAM/SOM, dan batas penggunaan AI maksimal 30%). Jangan memberikan jawaban yang singkat, dangkal, atau sekadar template generik.

PENTING - CATATAN TAMBAHAN PROPOSAL (Terapkan parameter ini secara detail dalam evaluasi dan rekomendasi kamu):
1. AI DETECTION & ETIKA: Ingatkan siswa bahwa jika teks ditulis menggunakan AI, sangat disarankan untuk diparafrase manual (bisa dicek dengan Turnitin AI). Penggunaan AI untuk visual/video proposal diperbolehkan asalkan diberi label "image generated by AI for visualization".
2. RINGKASAN EKSEKUTIF (RE): RE Tahap 2 idealnya 1 halaman yang sudah memuat landasan berdirinya usaha, solusi, UVP, target pasar, hasil validasi pasar, mitra kerjasama, dan finansial (HPP, BEP, dll). RE ini harus jauh lebih lengkap dari Tahap 1.
3. LATAR BELAKANG: Evaluasi apakah siswa mencantumkan data pendukung dari internet (jurnal/berita/Google Trends) yang dipadukan dengan pengalaman pribadi. Di akhir paragraf, harus ada highlight rumusan masalah/inti permasalahan.
4. SOLUSI / PRODUK / PROTOTYPE (Supply-Demand):
   - Foto produk harus besar & jelas, beri tanda panah atau highlight pada setiap fitur.
   - Jangan mendeskripsikan produk panjang lebar secara full-text. Gunakan visual, point-point, dan mainkan aspek DKV agar UVP tersorot.
   - Alur proses produksi harus dijelaskan menggunakan tabel/workflow/diagram, dan wajib dilampirkan foto nyata setiap tahapan produksinya agar terlihat riil.
   - Perbandingan kompetitor sebaiknya menggunakan tabel atau 4-quadrant brand positioning (kombinasi aspek visual dan penjelasan singkat).
   - Tarik benang merah (Supply-Demand): Fitur produk harus dinarasikan seolah-olah menjadi "jawaban" atas permasalahan di latar belakang (tanpa terkesan terlalu 'pick me').
   - Wajib menyoroti bahan baku utama dan aspek kearifan lokalnya dengan jelas (jangan hanya disebutkan sekilas).
5. TARGET PASAR & UKURAN PASAR:
   - Persona target pasar (umur, pekerjaan, budget, dll) harus inline/konsisten dengan baseline data pertanyaan di GForm. Usaha harus memiliki target spesifik, jangan terkesan maruk mau menargetkan semua orang (B2B/B2G juga diperbolehkan asal personanya spesifik).
   - Ukuran pasar (TAM, SAM, SOM) dimasukkan secara manual (kalkulasi mandiri).
   - KRUSIAL: Angka SOM harus sama/sinkron dengan angka target penjualan di tahun pertama pada tabel Finance. (Jangan ada ketidaksinkronan angka antar bagian).
6. HASIL VALIDASI PASAR: Jika ada masukan perbaikan produk (feedback) dari hasil kuesioner/GForm, tuliskan secara transparan dan jadikan itu sebagai celah untuk "next improvement".
7. OPERASIONAL & MITRA:
   - Awali penjelasan operasional dengan menjabarkan struktur usaha (pembagian scope dan responsibilities antara ketua dan anggota).
   - Foto ketika berdiskusi/ke tempat mitra harus lengkap.
   - Penjelasan harus memperlihatkan jelas peran setiap mitra (Mitra A untuk bagian apa, Mitra B bagian apa), key partners, key resources, serta darimana asal bahan baku.
   - Gunakan pendekatan visual (kombinasi foto, tabel, kotak-kotak/diagram struktur), jangan murni teks panjang.
8. FINANCE:
   - Ingatkan siswa agar tidak memproyeksikan balik modal (BEP) di 1-2 bulan pertama karena tidak realistis.
   - Penentuan harga jual harus didasarkan pada hasil survei (WTP) di GForm (tarik benang merah).
   - Pastikan komponen biaya memasukkan gaji pendiri, biaya pemasaran, dan biaya operasional bulanan rutin di luar HPP (tidak hanya HPP saja).
   - Sangat disarankan untuk menyertakan rasio finansial lain seperti ROI, NPV, IRR, dan RC Ratio agar lebih komprehensif dari sekadar BEP.
9. IMPLEMENTASI:
   - Fokuskan roadmap dan mitigasi risiko pada 1 bulan, 3 bulan, 6 bulan, hingga maksimal 2 tahun ke depan. Jangan berhalusinasi menyusun roadmap 5-10 tahun ke depan yang belum konkret.
   - Jelaskan dengan gamblang di bulan ke berapa akan mulai berjualan dan apa langkah mitigasi risikonya.

Evaluasi dilakukan berdasarkan 4 Komponen Utama dengan kriteria sangat spesifik sesuai Panduan FIKSI 2026 & Tabel Audit Kesiapan:

1. Purwarupa Produk/Jasa (MVP) (Bobot 30%):
   Evaluasi dilakukan dengan mengacu pada kode audit berikut:
   - [P-01] Visualisasi Purwarupa Otentik: Harus berupa foto asli produk jadi skala lab dari beberapa sudut (kemasan luar, isi, detail tekstur) atau gambar teknik orthographic presisi lengkap dimensi ukuran. Khusus aplikasi/digital, harus berupa mockup interaktif (Canva/Figma) yang bisa diklik membentuk alur navigasi (user flow). Jasa/Travel: Service Blueprint visual alur perjalanan pelanggan. Red Flag: Gambar hasil comotan internet (Google/Pinterest) tanpa modifikasi nyata.
   - [P-02] Alur Proses Produksi & [P-03] Keberlanjutan Bahan Baku Lokal: Adanya flowchart pembuatan produk yang logis skala SMA, resep rahasia/spesifikasi bahan baku lokal yang melimpah dan stabil pasokannya (Kearifan Lokal), dan SOP manajemen limbah (Zero Waste/circular economy atau pembuangan aman). Red Flag: Alur tidak logis, terlalu rumit layaknya pabrik industri besar, atau bahan baku langka/impor/merusak lingkungan.
   - [P-04] Pembagian Kerja Tim: Matriks pembagian peran tim yang adil secara kompetensi (CEO/CFO vs CPMO) dengan deskripsi kerja harian yang nyata (maksimal 2 orang). Red Flag: Peran tumpang tindih atau hanya formalitas nama saja.
   - [P-05] Bukti Pengujian Fungsi Purwarupa & Feedback Loop: Hasil uji organoleptik (F&B), uji ketahanan fisik/ergonomis (kriya/fashion), atau usability testing (aplikasi/jasa) oleh pengguna. Adanya bukti iterasi (formula sebelum vs sesudah validasi/The Entrepreneur Pivot). Red Flag: Purwarupa hanya dipajang sebagai konsep visual pasif tanpa bukti core function pernah dihidupkan/dicicipi/diuji.
   - Evaluasi kelima kriteria di atas untuk mengisi boolean array "checklist" secara berurutan:
     [1. Foto/video produk nyata/prototipe fisik, 2. Mockup/wireframe interaktif Figma/Canva, 3. Hasil uji coba awal/percobaan, 4. Testimoni/feedback early adopter, 5. Blueprint/ilustrasi teknis cara kerja]

2. Validasi Pasar (Bobot 25%):
   Evaluasi dilakukan dengan mengacu pada kode audit berikut:
   - [V-01] Objektivitas Responden Survei & [V-02] Karakteristik Early Adopter Spesifik: Survei kuantitatif minimal kepada 30-50 responden objektif yang mewakili segmen early adopter spesifik, bukan sekadar generalisasi kaku seperti "semua kalangan" atau "semua umur". Red Flag: Responden survei 100% berasal dari teman sekelas, satu sekolah, atau keluarga (bias tinggi).
   - [V-03] Bukti Autentik Dokumentasi Lapangan & [V-04] Analisis Grafik Struktur 3 Pilar: Setiap grafik hasil survei harus dianalisis menggunakan 3 Pilar: The Fact (Fakta angka), The Insight (Makna bisnis), dan The Action (Tindakan perbaikan tim). Dilengkapi foto/video tim menyodorkan sampel atau wawancara mendalam (Empathy Map/Word Cloud). Red Flag: Hanya menyalin (copy-paste) diagram bulat Google Form tanpa penjelasan strategis atau dokumentasi fisik lapangan.
   - [V-05] Analisis Kompetitor & UVP: Matriks perbandingan fitur/layanan/harga dengan minimal 2-3 kompetitor langsung, serta keunggulan unik (Unique Value Proposition - UVP) yang ramah lingkungan/kearifan lokal. Red Flag: Klaim sepihak tidak memiliki kompetitor.
   - [V-06] Validasi Finansial Pasar (WTP): Pertanyaan kesediaan membayar (Willingness to Pay) dalam survei untuk mengunci nominal harga jual. Red Flag: Harga jual ditentukan tanpa survei WTP.
   - [V-07] Bukti Komitmen Pembelian Nyata: Adanya waiting list, komitmen Pre-Order (PO) berbayar/DP, atau Surat Minat Kerja Sama (Letter of Intent - LoI) tertulis dari mitra/pembeli besar. Red Flag: Hanya janji verbal tanpa bukti konkret.
   - Evaluasi kelima kriteria di atas untuk mengisi boolean array "checklist" secara berurutan:
     [1. Survei terstruktur >= 30 responden, 2. Wawancara mendalam, 3. Bukti kebutuhan nyata/data tervalidasi, 4. Analisis kompetitor, 5. Bukti demand (pre-order/waiting list/LoI)]

3. Kelayakan Usaha & Finansial (Bobot 25%):
   Evaluasi dilakukan dengan mengacu pada kode audit berikut:
   - [F-01] Akurasi Perhitungan HPP & [F-02] Logika Sinkronisasi Harga Jual: Perhitungan HPP teliti dengan rumus HPP = (Total Biaya Variabel per Batch + Biaya Operasional Habis Pakai) / Total Unit. Harus mencantumkan semua biaya tersembunyi (kemasan, kuota internet, transportasi, penyusutan laptop/alat). Harga jual harus di atas HPP (mengamankan margin kotor sehat 40-60%) dan di bawah batas maksimal WTP hasil survei. Red Flag: Menuliskan biaya laptop/internet pribadi Rp0, HPP tidak realistis, atau harga jual melebihi WTP pasar.
   - [F-03] Realisme Perhitungan Balik Modal (BEP): Menghitung BEP unit & rupiah berdasarkan biaya tetap awal (Fixed Cost: sealer, spanduk, mesin) dibagi margin kotor per unit. Red Flag: Target penjualan harian/bulanan untuk BEP tidak logis (misal balik modal dalam 3 hari).
   - [F-04] Proyeksi Arus Kas Multi-Skenario: Proyeksi cashflow 12 bulan ke depan dengan Model Konservatif (terburuk, laku 30%) dan Model Optimis/Optimum. Red Flag: Proyeksi muluk-muluk selalu naik lurus tajam tanpa simulasi penurunan/risiko.
   - [F-05] Peta Persaingan & Mitigasi Risiko: Matriks mitigasi risiko teknis & pasar (Rencana B/Pivot) jika bahan baku naik 15% atau promosi sepi.
   - [F-06] Alokasi Modal Kerja yang Jelas: Rencana penggunaan dana modal (misal dari hadiah) dengan pembagian taktis 40% operasional, 30% alat tetap, 20% pemasaran, dan 10% dana darurat. Red Flag: Alokasi dana asal-asalan didominasi konsumsi/gaji tim berlebih.
   - Evaluasi kelima kriteria di atas untuk mengisi boolean array "checklist" secara berurutan:
     [1. Proyeksi keuangan realistis 12 bulan, 2. Analisis BEP akurat, 3. Identifikasi risiko + mitigasi, 4. Model keberlanjutan bisnis, 5. Struktur biaya lengkap (tetap, variabel, biaya awal)]

4. Rencana Implementasi & Tema (Bobot 20%):
   Evaluasi dilakukan dengan mengacu pada kode audit berikut:
   - [I-01] Garis Waktu Kerja Runtut (Gantt Chart): Timeline bulanan 12 bulan pasca-lomba yang detail per minggu dengan target luaran (output) konkret di setiap fase (Bulan 1: Optimasi/Pivot, Bulan 3: Soft Launch/Pre-order & cuan pertama, Bulan 6: MoU/LoI konsinyasi, Bulan 12: Akselerasi teknologi digital). Red Flag: Timeline asal tulis tanpa target luaran yang bisa diukur.
   - [I-02] Detail Taktis Strategi Pemasaran: Taktik digital pemasaran terperinci (organic content, micro-influencer, gerilya bazar sekolah, sistem konsinyasi) bukan kalimat umum. Red Flag: Hanya menyebut "promosi media sosial" tanpa detail.
   - [I-03] Rencana Cadangan (Pivot & Mitigasi): Rencana cadangan (Rencana B) jika rencana utama gagal. Red Flag: Proposal seolah tanpa celah/risiko.
   - [I-04] Integrasi Dampak Ekonomi Hijau & Sosial: Keselarasan dengan tema besar FIKSI (Ekonomi Hijau/Green Economy, kearifan lokal, Ekonomi Kreatif/Digital) dan prinsip Triple Bottom Line (People, Planet, Profit). Red Flag: Berpotensi merusak lingkungan atau mengabaikan warga sekitar.
   - [I-05] Pemanfaatan Teknologi Digital: Akselerasi operasional menggunakan teknologi digital (otomasi spreadsheet/App Sheet, Google Form/Sheets otomatis) untuk menekan biaya admin. Red Flag: Operasional dikerjakan manual tanpa digitalisasi.
   - Evaluasi kelima kriteria di atas untuk mengisi boolean array "checklist" secara berurutan:
     [1. Gantt Chart detail per minggu, 2. Strategi pemasaran digital konkret, 3. Rencana kolaborasi mitra eksternal, 4. KPI dan target jelas per milestone, 5. Pembagian tugas tim spesifik & realistis]

Format Skema Keluaran JSON:
Harus berupa objek JSON yang valid dan bersih dengan skema di bawah ini. Harap diperhatikan bahwa rekomendasi dan saran harus menghindari kata "wajib" (ganti dengan "disarankan"), menggunakan panggilan "kamu" (hindari kata "Anda"), dan tidak menggunakan kata "juri" (gunakan "model AI").

{
  "overallScore": number,
  "status": "SIAP JUARA" | "DIPERLUKAN PERBAIKAN" | "KURANG",
  "mvp": {
    "score": number (maksimal 30),
    "status": "BAGUS" | "CUKUP" | "KURANG",
    "realita": string (jelaskan realita draf proposal terkait MVP, min 4-6 kalimat),
    "ideal": string (jelaskan kondisi ideal MVP yang merujuk panduan, min 4-6 kalimat),
    "checklist": [boolean, boolean, boolean, boolean, boolean],
    "bagus": [string],
    "perbaiki": [string],
    "rekomendasi": string (saran konkret perbaikan MVP, min 4-6 kalimat. TANPA KATA "WAJIB" [GUNAKAN "DISARANKAN"], GUNAKAN SAPAAN "KAMU" [HINDARI "ANDA"], DAN JANGAN SEBUT KATA "JURI" [GUNAKAN "MODEL AI"])
  },
  "market": {
    "score": number (maksimal 25),
    "status": "BAGUS" | "CUKUP" | "KURANG",
    "realita": string (min 4-6 kalimat),
    "ideal": string (min 4-6 kalimat),
    "checklist": [boolean, boolean, boolean, boolean, boolean],
    "bagus": [string],
    "perbaiki": [string],
    "rekomendasi": string (saran konkret, TANPA KATA "WAJIB" [GUNAKAN "DISARANKAN"], GUNAKAN SAPAAN "KAMU" [HINDARI "ANDA"], DAN JANGAN SEBUT KATA "JURI" [GUNAKAN "MODEL AI"])
  },
  "finance": {
    "score": number (maksimal 25),
    "status": "BAGUS" | "CUKUP" | "KURANG",
    "realita": string (min 4-6 kalimat),
    "ideal": string (min 4-6 kalimat),
    "checklist": [boolean, boolean, boolean, boolean, boolean],
    "bagus": [string],
    "perbaiki": [string],
    "rekomendasi": string (saran konkret, TANPA KATA "WAJIB" [GUNAKAN "DISARANKAN"], GUNAKAN SAPAAN "KAMU" [HINDARI "ANDA"], DAN JANGAN SEBUT KATA "JURI" [GUNAKAN "MODEL AI"])
  },
  "implementation": {
    "score": number (maksimal 20),
    "status": "BAGUS" | "CUKUP" | "KURANG",
    "realita": string (min 4-6 kalimat),
    "ideal": string (min 4-6 kalimat),
    "checklist": [boolean, boolean, boolean, boolean, boolean],
    "bagus": [string],
    "perbaiki": [string],
    "rekomendasi": string (saran konkret, TANPA KATA "WAJIB" [GUNAKAN "DISARANKAN"], GUNAKAN SAPAAN "KAMU" [HINDARI "ANDA"], DAN JANGAN SEBUT KATA "JURI" [GUNAKAN "MODEL AI"])
  },
  "sustainability": {
    "pillarMatch": string (keselarasan pilar Ekonomi Hijau/Kreatif/Digital),
    "sdgAdvice": string (saran hubungan dengan SDGs PBB, TANPA KATA "WAJIB" [GUNAKAN "DISARANKAN"], GUNAKAN SAPAAN "KAMU" [HINDARI "ANDA"], DAN JANGAN SEBUT KATA "JURI" [GUNAKAN "MODEL AI"]),
    "riskMitigation": string (saran mitigasi risiko bisnis, TANPA KATA "WAJIB" [GUNAKAN "DISARANKAN"], GUNAKAN SAPAAN "KAMU" [HINDARI "ANDA"], DAN JANGAN SEBUT KATA "JURI" [GUNAKAN "MODEL AI"])
  },
  "summaryAdvice": string (ringkasan saran model AI secara keseluruhan, yang memuat ulasan keselarasan ide dengan tema FIKSI 2026 "Inovasi dan Teknologi Berbasis Kearifan Lokal" beserta saran konkret pemanfaatan/penambahan teknologi jika belum ada, minimal 4-6 kalimat. TANPA KATA "WAJIB" (GUNAKAN "DISARANKAN"), GUNAKAN SAPAAN "KAMU" (HINDARI "ANDA"), DAN JANGAN GUNAKAN KATA "JURI" (GUNAKAN "MODEL AI")),
  "extractedFinance": {
    "serverCost": number,
    "internetCost": number,
    "softwareCost": number,
    "depreciationCost": number,
    "rawMaterials": number,
    "transportCost": number,
    "marketingCost": number,
    "sellingPrice": number,
    "prodQty": number
  },
  "extractedWTP": {
    "tier1": number,
    "tier2": number,
    "tier3": number,
    "tier4": number,
    "tier5": number
  },
  "extractedGantt": [
    {
      "name": string,
      "member": string,
      "startWeek": number,
      "endWeek": number,
      "progress": number,
      "color": string (hex color: #3b82f6 | #10b981 | #f59e0b | #ec4899 | #8b5cf6)
    }
  ],
  "extractedSDGs": {
    "pillar": "hijau" | "kreatif" | "digital",
    "selectedSDGId": 8 | 9 | 12 | 13 | 15
  }
}
`;

function extractJSON(text) {
  // 1. Try to extract from ```json ... ``` or ``` ... ```
  const codeBlockRegex = /```(?:json)?\s*([\s\S]*?)```/g;
  let match;
  while ((match = codeBlockRegex.exec(text)) !== null) {
    try {
      return JSON.parse(match[1].trim());
    } catch (e) {
      // Continue
    }
  }

  // 2. Try to find JSON object starting with {"overallScore" or similar
  const overallScoreIndex = text.lastIndexOf('"overallScore"');
  if (overallScoreIndex !== -1) {
    const openBraceIndex = text.lastIndexOf('{', overallScoreIndex);
    if (openBraceIndex !== -1) {
      for (let i = text.length; i > openBraceIndex; i--) {
        const candidate = text.substring(openBraceIndex, i);
        try {
          return JSON.parse(candidate.trim());
        } catch (e) {
          // Continue
        }
      }
    }
  }

  // 3. Fallback: find any valid JSON object from the end of the text
  let braceIndex = text.lastIndexOf('{');
  while (braceIndex !== -1) {
    for (let i = text.length; i > braceIndex; i--) {
      const candidate = text.substring(braceIndex, i);
      try {
        return JSON.parse(candidate.trim());
      } catch (e) {
        // Continue
      }
    }
    braceIndex = text.lastIndexOf('{', braceIndex - 1);
  }

  throw new Error("Tidak dapat mem-parse output sebagai JSON yang valid.");
}

export async function POST(req) {
  try {
    let proposalText = '';
    let userApiKey = '';

    const contentType = req.headers.get('content-type') || '';

    if (contentType.includes('multipart/form-data')) {
      // Handle file upload
      const formData = await req.formData();
      const file = formData.get('file');
      userApiKey = formData.get('userApiKey') || '';

      if (!file) {
        return new Response(JSON.stringify({ error: 'File proposal tidak ditemukan dalam unggahan.' }), {
          status: 400,
          headers: { 'Content-Type': 'application/json' }
        });
      }

      // Convert file into a Buffer and extract text using pdf-parse
      const arrayBuffer = await file.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);

      const pdf = require('pdf-parse');
      const pdfData = await pdf(buffer);
      proposalText = pdfData.text;

    } else {

      // Handle JSON body (fallback compatibility for templates)
      const body = await req.json();
      proposalText = body.proposalText;
      userApiKey = body.userApiKey || '';
    }


    if (!proposalText || proposalText.trim().length < 10) {
      return new Response(JSON.stringify({ error: 'Gagal mengekstrak teks proposal. Pastikan PDF berisi teks (bukan hasil scan gambar) dan tidak kosong.' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Validate custom API key format if provided
    if (userApiKey) {
      const cleanKey = userApiKey.trim();
      if (!cleanKey.startsWith('AIzaSy') || cleanKey.length < 30) {
        return new Response(JSON.stringify({
          error: 'Format API Key Google Gemini tidak valid. Kunci harus diawali dengan "AIzaSy" dan biasanya berjumlah 39 karakter.'
        }), {
          status: 400,
          headers: { 'Content-Type': 'application/json' }
        });
      }
    }

    // Determine which API key to use
    const apiKey = userApiKey ? userApiKey.trim() : process.env.GEMINI_API_KEY;

    if (!apiKey) {
      // If no API Key, return mock data simulated analysis based on input keywords
      const mockResult = generateMockAnalysis(proposalText);
      return new Response(JSON.stringify(mockResult), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Call real Gemini API
    const ai = new GoogleGenerativeAI(apiKey);
    const model = ai.getGenerativeModel({
      model: 'gemma-4-31b-it',
      systemInstruction: SYSTEM_INSTRUCTIONS
    });

    const prompt = `Berikut adalah proposal bisnis dari siswa:
----------------------------------------
${proposalText}
----------------------------------------
Analisis proposal ini secara objektif dan detail. Kembalikan tanggapan hanya dalam format JSON sesuai skema.`;

    let result;
    try {
      result = await model.generateContent({
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        generationConfig: {
          responseMimeType: 'application/json'
        }
      });
    } catch (err) {
      if (err.message && err.message.includes('404')) {
        let availableModels = '';
        try {
          const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`);
          const data = await res.json();
          if (data.models) {
            availableModels = data.models.filter(m => m.name.toLowerCase().includes('gemma') || m.name.toLowerCase().includes('gemini')).map(m => m.name).join(', ');
          }
        } catch (fetchErr) {
          availableModels = 'Gagal mengambil daftar model.';
        }
        throw new Error(`Model tidak ditemukan. Model yang tersedia dengan API Key ini: ${availableModels}. Original Error: ${err.message}`);
      }
      throw err;
    }

    const responseText = result.response.text();
    let jsonResult;
    try {
      jsonResult = extractJSON(responseText);
    } catch (err) {
      throw new Error(`Output JSON gagal di-parse: ${err.message}. Raw output: ${responseText}`);
    }


    return new Response(JSON.stringify(jsonResult), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });


  } catch (error) {
    console.error('Error in evaluate route:', error);

    // Sanitize error message to ensure no API key info is leaked
    let safeMessage = error.message || 'Terjadi kesalahan internal.';
    if (safeMessage.includes('AIzaSy')) {
      safeMessage = 'Autentikasi gagal. Pastikan API Key Google Gemini yang kamu masukkan sudah benar.';
    }

    return new Response(JSON.stringify({
      error: 'Gagal menganalisis proposal.',
      details: safeMessage
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}

// Function to generate high-quality mock evaluation responses if API key is not supplied
function generateMockAnalysis(text) {
  const lowercase = text.toLowerCase();

  // Custom mock values based on templates or keywords in the text
  let isRiceDetector = lowercase.includes('gabah') || lowercase.includes('padi') || lowercase.includes('rice') || lowercase.includes('sensor');
  let isUpcycle = lowercase.includes('cangkang') || lowercase.includes('udang') || lowercase.includes('limbah') || lowercase.includes('upcycle') || lowercase.includes('plastik');
  let isGame = lowercase.includes('game') || lowercase.includes('permainan') || lowercase.includes('sejarah') || lowercase.includes('budaya');

  let title = "Ide Bisnis Kustom";
  let score = 74;
  let status = "DIPERLUKAN PERBAIKAN";

  if (isRiceDetector) {
    title = "Sensor Pendeteksi Kualitas Gabah Berbasis IoT (RiceGuard)";
    score = 88;
    status = "SIAP JUARA";
  } else if (isUpcycle) {
    title = "Upcycling Cangkang Udang Menjadi Bioplastik Organik (EcoShell)";
    score = 92;
    status = "SIAP JUARA";
  } else if (isGame) {
    title = "Game Edukasi Sejarah & Budaya Nusantara (Garuda Saga)";
    score = 78;
    status = "DIPERLUKAN PERBAIKAN";
  }

  const result = {
    overallScore: score,
    status: status,
    mvp: {
      score: score > 80 ? 25 : 10,
      status: score > 80 ? "BAGUS" : "KURANG",
      realita: isRiceDetector
        ? "Sudah melampirkan screenshot desain sirkuit sensor dan mockup antarmuka web monitoring."
        : isGame
          ? "Hanya menampilkan gambar coretan karakter di kertas buram dan logo rancangan game tanpa alur."
          : "Menjelaskan konsep ide digital secara tekstual, namun visualisasi purwarupa atau screenshoot sistem belum terlampir secara rapi.",
      ideal: "Menampilkan desain antarmuka (UI/UX Mockup) yang rapi, modern, konsisten dalam warna/tipografi, fungsional, dilengkapi bagan alir (flowchart) navigasi pengguna serta video rekaman layar (screencast) demonstrasi berdurasi 1-2 menit di GDrive.",
      checklist: isRiceDetector ? [true, true, true, false, false] : isGame ? [true, false, false, false, false] : [true, true, false, false, false],
      bagus: [
        "Ide dan nama produk sudah terdefinisi dengan jelas",
        "Deskripsi fungsi produk mudah dipahami pembaca",
        "Target segmen pengguna sudah diidentifikasi"
      ],
      perbaiki: [
        "Tidak ada foto, video, atau visual produk nyata sama sekali",
        "Tidak ada prototipe fisik maupun mockup digital interaktif",
        "Tidak ada data hasil uji coba atau percobaan awal",
        "Tidak ada testimoni atau feedback dari calon pengguna",
        "Tidak ada blueprint atau diagram teknis cara kerja produk"
      ],
      rekomendasi: isGame
        ? "Segera dokumentasikan bukti nyata: (1) Buat mockup di Figma/Canva dan lampirkan screenshot-nya. (2) Foto proses pembuatan produk, walau masih dalam tahap awal. (3) Hubungi minimal 5 calon pengguna dan minta feedback tertulis untuk dijadikan lampiran. (4) Buat halaman landing page sederhana dan lampirkan link-nya sebagai bukti validasi awal."
        : "Segera dokumentasikan bukti nyata: (1) Buat mockup di Figma/Canva dan lampirkan screenshot-nya. (2) Foto proses pembuatan produk, walau masih dalam tahap awal. (3) Hubungi minimal 5 calon pengguna dan minta feedback tertulis untuk dijadikan lampiran. (4) Buat halaman landing page sederhana dan lampirkan link-nya sebagai bukti validasi awal."
    },
    market: {
      score: score > 85 ? 20 : 11,
      status: score > 85 ? "BAGUS" : "CUKUP",
      realita: isUpcycle
        ? "Telah menguji produk bioplastik ke 25 pengrajin lokal dan melampirkan grafik kepuasan serta hasil survei WTP harga jual."
        : "Menyatakan telah melakukan pengujian produk ke beberapa keluarga terdekat dan teman sekelas tanpa melampirkan grafik umpan balik kuantitatif.",
      ideal: "Pengujian langsung ke minimal 15-30 orang target pengguna riil secara objektif, menyajikan tabel feedback loop (Sebelum vs Sesudah perbaikan konkret), serta menetapkan harga jual rasional berbasis kurva Willingness to Pay (WTP).",
      checklist: isUpcycle ? [true, true, true, true, false] : [true, true, true, false, false],
      bagus: [
        "Identifikasi segmen target pasar sudah ada dan spesifik",
        "Pemahaman masalah pelanggan cukup baik secara naratif",
        "Sudah ada survei awal (walau jumlah responden masih sedikit)"
      ],
      perbaiki: [
        "Survei hanya dilakukan kepada 10 responden (minimum: 30)",
        "Tidak ada wawancara mendalam (in-depth interview) yang terdokumentasi",
        "Analisis kompetitor tidak terstruktur — hanya menyebutkan nama tanpa komparasi fitur/harga",
        "Tidak ada bukti pre-order, waiting list, atau minat nyata dari calon pelanggan"
      ],
      rekomendasi: "Perkuat validasi pasar dengan: (1) Perluas survei ke minimal 30 responden target pasar dengan menggunakan Google Form — sertakan link dan data rekapitulasi di lampiran. (2) Lakukan dan rekam wawancara mendalam dengan 3–5 calon pelanggan potensial. (3) Buat tabel perbandingan kompetitor (nama, harga, fitur, kelebihan/kekurangan vs produk kamu). (4) Buka pre-order simbolis atau daftar waiting list untuk membuktikan demand nyata."
    },
    finance: {
      score: score > 80 ? 22 : 13,
      status: score > 80 ? "BAGUS" : "CUKUP",
      realita: lowercase.includes('keuangan') || lowercase.includes('bep')
        ? "Mencantumkan perhitungan modal dasar, tetapi mengabaikan biaya sewa server bulanan, internet tim, dan penyusutan aset laptop kerja."
        : "Menyebutkan biaya operasional Rp0 karena menggunakan laptop pribadi dan wifi sekolah, serta proyeksi keuntungan naik 500% di bulan kedua.",
      ideal: "Menyusun struktur paket harga langganan atau produk yang logis, memaparkan rincian biaya operasional bulanan riil (server, internet, transportasi, penyusutan laptop), dan menghitung Break-Even Point (BEP Unit & BEP Rupiah) dengan grafik proyeksi 6 bulan yang realistis.",
      checklist: lowercase.includes('keuangan') ? [true, true, true, false, false] : [true, true, false, false, false],
      bagus: [
        "Harga jual produk sudah ditetapkan dengan angka yang spesifik",
        "Margin keuntungan per unit positif (revenue > COGS per unit)",
        "Sudah ada perhitungan BEP walaupun masih sederhana",
        "Target produksi bulanan sudah ditentukan"
      ],
      perbaiki: [
        "Biaya tetap (server, listrik, peralatan) tidak dicantumkan — BEP jadi tidak realistis",
        "Proyeksi keuangan hanya untuk 1 bulan, bukan 12 bulan",
        "Tidak ada analisis risiko — tidak ada matriks risiko maupun strategi mitigasi",
        "Tidak ada skenario keuangan alternatif (best-case / worst-case)"
      ],
      rekomendasi: "Perbaiki kelayakan finansial: (1) Inventarisasi SEMUA biaya awal dan operasional, termasuk packaging, listrik, transportasi, dan biaya promosi — masukkan sebagai biaya tetap amortisasi. (2) Buat proyeksi keuangan 12 bulan dengan asumsi pertumbuhan 10%/bulan. (3) Tambahkan matriks risiko dengan minimal 5 risiko utama beserta strategi mitigasinya. (4) Buat dua skenario: optimis (target tercapai 100%) dan pesimis (target hanya 50%)."
    },
    implementation: {
      score: score > 80 ? 18 : 8,
      status: score > 80 ? "BAGUS" : "KURANG",
      realita: isRiceDetector
        ? "Melampirkan Gantt Chart pembagian tugas mingguan dan bukti komunikasi WhatsApp awal dengan koperasi petani gabah lokal."
        : "Menjelaskan rencana promosi klise 'mulut ke mulut dan lewat medsos', tanpa melampirkan pembagian jadwal kerja mingguan (Gantt chart) atau bukti kemitraan riil.",
      ideal: "Gantt Chart mingguan yang memisahkan jam sekolah dengan kerja bisnis, pembagian job desk personal tim, draf poster promosi visual medsos spesifik target, bukti dokumentasi/chat dengan penyuplai bahan baku, dan foto kolaborasi lapangan dengan mitra lokal.",
      checklist: isRiceDetector ? [true, true, true, false, false] : [true, true, false, false, false],
      bagus: [
        "Struktur tim sudah disebutkan beserta nama masing-masing anggota",
        "Kegiatan-kegiatan utama sudah teridentifikasi secara umum",
        "Ada rencana penggunaan media sosial sebagai kanal pemasaran"
      ],
      perbaiki: [
        "Gantt Chart hanya per bulan (tidak per minggu) dan tidak ada deliverable per milestone",
        "Strategi digital marketing hanya 'pakai Instagram/TikTok' tanpa rencana konten, target, atau anggaran",
        "Tidak ada rencana kolaborasi dengan pihak eksternal (mitra, sponsor, komunitas)",
        "Tidak ada KPI terukur — tidak ada target follower, konversi, atau revenue per periode",
        "Pembagian tugas tidak mencerminkan kompetensi spesifik anggota"
      ],
      rekomendasi: "Perkuat rencana implementasi: (1) Buat Gantt Chart per minggu dengan sub-task dan deliverable spesifik. (2) Rancang konten kalender media sosial untuk 3 bulan pertama beserta target engagement-nya. (3) Identifikasi dan hubungi minimal 2 calon mitra/kolaborator eksternal. (4) Tentukan KPI SMART (Specific, Measurable, Achievable, Relevant, Time-bound) per bulan."
    },
    sustainability: {
      pillarMatch: isUpcycle
        ? "Sangat kuat di pilar Ekonomi Hijau (upcycling limbah cangkang udang) dan Ekonomi Digital (sistem e-commerce pasokan)."
        : isRiceDetector
          ? "Linear dengan pilar Ekonomi Digital (sensor IoT) dan Ekonomi Hijau (mengurangi gagal panen padi sehingga menekan food waste)."
          : "Cocok dengan Ekonomi Kreatif (game budaya) dan Ekonomi Digital, namun kontribusi terhadap Ekonomi Hijau (keberlanjutan lingkungan) masih lemah.",
      sdgAdvice: isUpcycle
        ? "Mendukung penuh SDG 12 (Konsumsi & Produksi Bertanggung Jawab) dan SDG 14 (Menjaga Ekosistem Laut dengan mengurangi sampah cangkang). Tonjolkan logo SDGs ini di halaman awal proposal."
        : "Sesuai dengan SDG 9 (Inovasi Industri) dan SDG 2 (Tanpa Kelaparan / Ketahanan Pangan). Sebutkan secara tertulis kontribusi ini pada Bab Pendahuluan proposal.",
      riskMitigation: "Rencana mitigasi risiko teknis (misal cadangan server mati, kegagalan sensor) harus dituliskan dalam tabel matriks risiko. Jadwalkan juga rencana pendaftaran Hak Cipta (HAKI) atau merk dagang pada roadmap bulan ke-4 setelah kompetisi."
    },
    summaryAdvice: isRiceDetector || isUpcycle
      ? `Ide bisnis "${title}" sangat berpotensi. Fokus perbaikan kamu saat ini adalah melengkapi visualisasi bukti sinergi mitra lapangan berupa foto dokumentasi fisik kegiatan, serta merinci roadmap perlindungan HAKI produk.`
      : `Proposal "${title}" memerlukan penguatan di bagian visual purwarupa digital (mockup figma), survei pasar yang lebih objektif (>15 orang), dan pembagian waktu operasional siswa agar tidak mengabaikan sekolah. Gunakan alat simulasi di bawah untuk memperbaikinya.`,
    extractedFinance: isRiceDetector ? {
      serverCost: 150000,
      internetCost: 100000,
      softwareCost: 50000,
      depreciationCost: 100000,
      rawMaterials: 25000,
      transportCost: 5000,
      marketingCost: 5000,
      sellingPrice: 75000,
      prodQty: 45
    } : isUpcycle ? {
      serverCost: 0,
      internetCost: 50000,
      softwareCost: 0,
      depreciationCost: 80000,
      rawMaterials: 1000,
      transportCost: 500,
      marketingCost: 500,
      sellingPrice: 2500,
      prodQty: 400
    } : {
      serverCost: 0,
      internetCost: 0,
      softwareCost: 0,
      depreciationCost: 0,
      rawMaterials: 0,
      transportCost: 0,
      marketingCost: 0,
      sellingPrice: 150000,
      prodQty: 10
    },
    extractedWTP: isRiceDetector ? {
      tier1: 30,
      tier2: 28,
      tier3: 20,
      tier4: 10,
      tier5: 3
    } : isUpcycle ? {
      tier1: 30,
      tier2: 30,
      tier3: 25,
      tier4: 15,
      tier5: 5
    } : {
      tier1: 5,
      tier2: 3,
      tier3: 1,
      tier4: 0,
      tier5: 0
    },
    extractedGantt: isRiceDetector ? [
      { name: 'Coding & Desain MVP', member: 'Budi (Developer)', startWeek: 1, endWeek: 3, progress: 80, color: '#3b82f6' },
      { name: 'Survei Validasi Pasar', member: 'Siti (Marketing)', startWeek: 2, endWeek: 4, progress: 100, color: '#10b981' },
      { name: 'Sinergi & Rapat Mitra', member: 'Budi & Siti', startWeek: 4, endWeek: 5, progress: 40, color: '#f59e0b' }
    ] : isUpcycle ? [
      { name: 'Ekstraksi Cangkang', member: 'Tim Kimia', startWeek: 1, endWeek: 4, progress: 90, color: '#ec4899' },
      { name: 'Uji Validasi Kemasan', member: 'Tim Marketing', startWeek: 3, endWeek: 5, progress: 80, color: '#10b981' }
    ] : [
      { name: 'Coding Game', member: 'Ketua Tim', startWeek: 1, endWeek: 6, progress: 20, color: '#3b82f6' }
    ],
    extractedSDGs: isRiceDetector ? {
      pillar: 'digital',
      selectedSDGId: 9
    } : isUpcycle ? {
      pillar: 'hijau',
      selectedSDGId: 12
    } : {
      pillar: 'kreatif',
      selectedSDGId: 8
    }
  };

  return result;
}
